Handyman Studio/Controllers/FaultsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Handyman_Studio.Models;
using Handyman_Studio.Utils;
using Microsoft.AspNet.Identity;

namespace Handyman_Studio.Controllers
{
    [Authorize]
    public class FaultsController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        // GET: Faults
        public ActionResult Index()
        {
            if (!AccessCheck.Read(User.Identity.Name, PanelId.Faults))
                return RedirectToAction("Index", "Home");

            var userId = db.Users.First(u => u.UserName == User.Identity.Name).Id;
            return View(db.Faults.Where(f => f.FaultStatus == 0 || f.ServicemanId == userId).ToList());
        }

        // GET: Faults/Details/5
        public ActionResult Details(Guid? id)
        {
            if (!AccessCheck.Read(User.Identity.Name, PanelId.Faults))
                return RedirectToAction("Index", "Home");

            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var fault = db.Faults.Find(id);
            if (fault == null) return HttpNotFound();
            return View(fault);
        }

        // GET: Faults/Create
        public ActionResult Create()
        {
            if (!AccessCheck.Write(User.Identity.Name, PanelId.Faults))
                return RedirectToAction("Index", "Home");

            var userId = db.Users.FirstOrDefault(user => user.Email == User.Identity.Name)?.Id;
            var model = new ProductFaultModel {UserProduct = db.Products.Where(p => p.OwnerId == userId).ToList()};

            return View(model);
        }

        // POST: Faults/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductFaultModel productFault)
        {
            if (!AccessCheck.Write(User.Identity.Name, PanelId.Faults))
                return RedirectToAction("Index", "Home");

            var user = db.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            var userId = user.Id;
            var userProducts = db.Products.Where(p => p.OwnerId == userId).ToList();

            productFault.Fault.FaultId = Guid.NewGuid();
            productFault.Fault.UserId = userId;
            productFault.Fault.ServicemanId = "Nie przydzielono";
            productFault.Fault.FaultStatus = Status.Open;
            productFault.Fault.FaultPartPrice = 0.0;
            productFault.Fault.FaultRepairPrice = 0.0;
            productFault.Fault.FaultSubject = productFault.SelectedProduct;
            productFault.Fault.FaultReportDate = DateTime.Now;
            productFault.Fault.FaultDescriptionService = "brak";
            productFault.UserProduct = userProducts;

            if (productFault.SelectedProduct == 0 || productFault.Fault.FaultRepairDate == null)
                return View(productFault);

            var log = new Log
            {
                Id = Math.Abs(DateTime.Now.GetHashCode() * DateTime.Now.Millisecond),
                InvolvedUserAccount = db.Users.FirstOrDefault(u => user.Email == User.Identity.Name)?.Email,
                OperationDateTime = DateTime.Now,
                OperationType = @"Fault creation",
                IpAddress = GetIpAddress(),
                UserId = userId,
                FaultId = productFault.Fault.FaultId,
                ProductId = productFault.SelectedProduct
            };

            db.Logs.Add(log);
            db.Faults.Add(productFault.Fault);
            db.SaveChanges();
            return RedirectToAction(user.GroupId == GroupId.Client ? "UserIndex" : "Index");
        }

        // GET: Faults/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (!AccessCheck.Write(User.Identity.Name, PanelId.Faults))
                return RedirectToAction("Index", "Home");

            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var fault = db.Faults.Find(id);
            if (fault == null) throw new InvalidOperationException();


            var faultedit = new FaultEditModel
            {
                FaultId = fault.FaultId,
                FaultRepairDate = (DateTime) fault.FaultRepairDate,
                FaultRepairPrice = fault.FaultRepairPrice,
                FaultStatus = fault.FaultStatus,
                FaultParts = db.FaultsParts
                    .Where(fp => fp.FaultId == fault.FaultId)
                    .Join(db.Parts, fp => fp.PartId, p => p.Id, (fp, p) => p)
                    .ToList()
            };

            return View(faultedit);
        }

        // POST: Faults/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FaultId,FaultRepairDate,FaultRepairPrice,FaultStatus")]
            FaultEditModel model)
        {
            if (!AccessCheck.Write(User.Identity.Name, PanelId.Faults))
                return RedirectToAction("Index", "Home");

            var fault = db.Faults.Find(model.FaultId);

            var log = new Log
            {
                Id = Math.Abs(DateTime.Now.GetHashCode() * DateTime.Now.Millisecond),
                InvolvedUserAccount = db.Users.FirstOrDefault(user => user.Email == User.Identity.Name)?.Email,
                OperationDateTime = DateTime.Now,
                OperationType = @"Faults edit failure",
                IpAddress = GetIpAddress(),
                UserId = db.Users.FirstOrDefault(user => user.Email == User.Identity.Name)?.Id,
                FaultId = fault.FaultId,
                ProductId = fault.FaultSubject
            };

            fault.FaultRepairDate = model.FaultRepairDate;
            fault.FaultRepairPrice = model.FaultRepairPrice;
            fault.FaultStatus = model.FaultStatus;

            if (!ModelState.IsValid) return View(model);

            log.OperationType = @"Faults edit success";
            db.Logs.Add(log);
            db.Entry(fault).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Claim(Guid id)
        {
            if (!AccessCheck.Write(User.Identity.Name, PanelId.Faults))
                return RedirectToAction("Index", "Home");

            var fault = db.Faults.Find(id);
            var log = new Log
            {
                Id = Math.Abs(DateTime.Now.GetHashCode() * DateTime.Now.Millisecond),
                InvolvedUserAccount = db.Users.FirstOrDefault(user => user.Email == User.Identity.Name)?.Email,
                OperationDateTime = DateTime.Now,
                OperationType = @"Claim fault failure",
                IpAddress = GetIpAddress(),
                UserId = db.Users.FirstOrDefault(user => user.Email == User.Identity.Name)?.Id,
                FaultId = id,
                ProductId = fault.FaultSubject
            };

            fault.ServicemanId = db.Users.First(u => u.UserName == User.Identity.Name).Id;
            fault.FaultStatus = Status.Working;

            if (!ModelState.IsValid)
            {
                db.Logs.Add(log);
                db.SaveChanges();
                return View("Index");
            }

            log.OperationType = @"Claim fault success";
            db.Logs.Add(log);
            db.Entry(fault).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ClaimFault(Guid id)
        {
            if (!AccessCheck.Write(User.Identity.Name, PanelId.Faults))
                return RedirectToAction("Index", "Home");

            var fault = db.Faults.Find(id);
            var log = new Log
            {
                Id = Math.Abs(DateTime.Now.GetHashCode() * DateTime.Now.Millisecond),
                InvolvedUserAccount = db.Users.FirstOrDefault(user => user.Email == User.Identity.Name)?.Email,
                OperationDateTime = DateTime.Now,
                OperationType = @"Claim fault failure",
                IpAddress = GetIpAddress(),
                UserId = db.Users.FirstOrDefault(user => user.Email == User.Identity.Name)?.Id,
                FaultId = id,
                ProductId = fault.FaultSubject
            };

            log.OperationType = @"Claim fault success";
            fault.ServicemanId = db.Users.First(m => m.UserName == User.Identity.Name).Id;
            db.Entry(fault).State = EntityState.Modified;

            db.Logs.Add(log);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Parts(FaultPartsModel model, string returnUrl)
        {
            if (!AccessCheck.Write(User.Identity.Name, PanelId.Faults))
                return RedirectToAction("Index", "Home");

            if (model.PartId != 0)
            {
                db.FaultsParts.Add(new FaultPart {FaultId = model.FaultId, PartId = model.PartId});
                db.SaveChanges();

                var fault = db.Faults.Find(model.FaultId);

                var sum = db.FaultsParts
                    .Join(db.Parts, fp => fp.PartId, p => p.Id, (fp, p) => new {fp.FaultId, Price = p.NetPrice})
                    .Where(el => el.FaultId == fault.FaultId)
                    .Sum(p => p.Price);

                if (fault != null)
                {
                    fault.FaultPartPrice = sum;
                    db.Entry(fault).State = EntityState.Modified;
                }

                db.SaveChanges();
                model.PartId = 0;
            }

            model.FaultParts = db.FaultsParts
                .Where(fp => fp.FaultId == model.FaultId)
                .Join(db.Parts, fp => fp.PartId, p => p.Id, (fp, p) => p)
                .ToList();

            model.AllParts = db.Parts.Where(p => !p.Hidden).ToList();

            return View(model);

Handyman Studio/Controllers/PartsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Handyman_Studio.Models;
using Handyman_Studio.Utils;

namespace Handyman_Studio.Controllers
{
    public class PartsController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        // GET: Parts
        public ActionResult Index()
        {
            if (!AccessCheck.Read(User.Identity.Name, PanelId.Parts))
                return RedirectToAction("Index", "Home");

            return View(db.Parts.ToList());
        }

        // GET: Parts/Details/5
        public ActionResult Details(int? id)
        {
            if (!AccessCheck.Read(User.Identity.Name, PanelId.Parts))
                return RedirectToAction("Index", "Home");

            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var part = db.Parts.Find(id);
            if (part == null) return HttpNotFound();
            return View(part);
        }

        // GET: Parts/Create
        public ActionResult Create()
        {
            if (!AccessCheck.Write(User.Identity.Name, PanelId.Parts))
                return RedirectToAction("Index", "Home");

            return View();
        }

        // POST: Parts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Hidden,NetPrice")]
            Part part)
        {
            if (!AccessCheck.Write(User.Identity.Name, PanelId.Parts))
                return RedirectToAction("Index", "Home");

            var log = new Log
            {
                Id = Math.Abs(DateTime.Now.GetHashCode() * DateTime.Now.Millisecond),
                InvolvedUserAccount = db.Users.FirstOrDefault(user => user.Email == User.Identity.Name)?.Email,
                OperationDateTime = DateTime.Now,
                OperationType = @"Part creation",
                IpAddress = GetIpAddress(),
                UserId = db.Users.FirstOrDefault(user => user.Email == User.Identity.Name)?.Id,
                PartId = part.Id
            };

            if (!ModelState.IsValid)
            {
                db.Logs.Add(log);
                db.SaveChanges();
                return View(part);
            }

            db.Logs.Add(log);
            db.Parts.Add(part);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Parts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!AccessCheck.Write(User.Identity.Name, PanelId.Parts))
                return RedirectToAction("Index", "Home");

            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var part = db.Parts.Find(id);
            if (part == null) return HttpNotFound();
            return View(part);
        }

        // POST: Parts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Hidden,NetPrice")]
            Part part)
        {
            if (!AccessCheck.Write(User.Identity.Name, PanelId.Parts))
                return RedirectToAction("Index", "Home");

            if (!ModelState.IsValid) return View(part);

            var log = new Log
            {
                Id = Math.Abs(DateTime.Now.GetHashCode() * DateTime.Now.Millisecond),
                InvolvedUserAccount = db.Users.FirstOrDefault(user => user.Email == User.Identity.Name)?.Email,
                OperationDateTime = DateTime.Now,
                OperationType = @"Part edit",
                IpAddress = GetIpAddress(),
                UserId = db.Users.FirstOrDefault(user => user.Email == User.Identity.Name)?.Id,
                PartId = part.Id
            };
            db.Logs.Add(log);
            db.Entry(part).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Parts/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!AccessCheck.Write(User.Identity.Name, PanelId.Parts))
                return RedirectToAction("Index", "Home");

            var part = db.Parts.Find(id);
            if (part != null)
            {
                db.Parts.Remove(part);
                var log = new Log
                {
                    Id = Math.Abs(DateTime.Now.GetHashCode() * DateTime.Now.Millisecond),
                    InvolvedUserAccount = db.Users.FirstOrDefault(user => user.Email == User.Identity.Name)?.Email,
                    OperationDateTime = DateTime.Now,
                    OperationType = @"Part delete",
                    IpAddress = GetIpAddress(),
                    UserId = db.Users.FirstOrDefault(user => user.Email == User.Identity.Name)?.Id,
                    PartId = part.Id
                };

                db.Logs.Add(log);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) db.Dispose();
            base.Dispose(disposing);
        }


        private string GetIpAddress()
        {
            var context = System.Web.HttpContext.Current;
            var ipAddress = context.Request.ServerVariables["HTTP_X_FORWARDED_FOR"];

            if (string.IsNullOrEmpty(ipAddress)) return context.Request.ServerVariables["REMOTE_ADDR"];
            var addresses = ipAddress.Split(',');
            return addresses.Length != 0 ? addresses[0] : context.Request.ServerVariables["REMOTE_ADDR"];
        }
    }
}

Handyman Studio/Views/Faults/Create.cshtml
@model Handyman_Studio.Models.ProductFaultModel

Using Date Template

@{
    ViewBag.Title = "Create";
}
<h2>Dodaj usterkę <span class="lnr lnr-poop"></span></h2>

   
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.Fault.FaultId);
        @Html.HiddenFor(m => m.Fault.FaultPartPrice);
        @Html.HiddenFor(m => m.Fault.FaultRepairPrice);
        @Html.HiddenFor(m => m.Fault.FaultStatus);
        @Html.HiddenFor(m => m.Fault.ServicemanId)
        @Html.HiddenFor(m => m.Fault.UserId)
        @Html.HiddenFor(m => m.Fault.FaultSubject)
        @Html.HiddenFor(m => m.Fault.FaultReportDate)
        @Html.HiddenFor(m => m.Fault.FaultDescriptionService)
        @Html.HiddenFor(m => m.UserProduct);


        <div class="form-horizontal">

            <div class="form-group">
                @Html.LabelFor(model => model.Fault.FaultSubject, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(m => m.SelectedProduct, new SelectList(Model.UserProduct, "Id", "SerialNumber", 0), "Wybierz produkt")
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Fault.FaultDescriptionUser, new { @class = "control-label col-md-2" })
                <div class="col-md-10 col-lg-10 col-xl-10">
                    @Html.TextAreaFor(model => model.Fault.FaultDescriptionUser, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Fault.FaultDescriptionUser, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Fault.FaultRepairDate, new { @class = "control-label col-md-2" })
                <div class="col-md-10 col-lg-10 col-xl-10">
                    @Html.TextBox("Fault.FaultRepairDate", "", new { @class = "datefield", type = "date" })
                    @Html.ValidationMessageFor(model => model.Fault.FaultRepairDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    @Html.ActionLink("Powrót do listy usterek", "UserIndex")

    <a href="UserIndex">
        <span class="lnr lnr-rocket"></span>
    </a>

Handyman Studio/Views/Faults/Details.cshtml
@model Handyman_Studio.Models.Fault

@{
    ViewBag.Title = "Details";
}

<h2>Szczegóły<span class="lnr lnr-star"></span></h2>

<div>
        
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultReportDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultReportDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultRepairDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultRepairDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultSubject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultSubject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultDescriptionUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultDescriptionUser)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.FaultDescriptionService)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultDescriptionService)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultPartPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultPartPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultRepairPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultRepairPrice)
        </dd>

    </dl>
</div>
<div class="col-xs-12">
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.FaultId }) <span class="lnr lnr-magic-wand"></span>
</div>
<div class="col-xs-12">
    @Html.ActionLink("Powrót do listy usterek", "Index") <span class="lnr lnr-rocket"></span>
</div>
    

Handyman Studio/Views/Faults/Edit.cshtml
@model Handyman_Studio.Models.FaultEditModel

@{
    ViewBag.Title = "Edit";
}
<h2>Edytuj usterkę<span class="lnr lnr-magic-wand"></span></h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.FaultId)

        <div class="form-group">
            @Html.LabelFor(model => model.FaultRepairDate, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.FaultRepairDate, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.FaultRepairDate, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FaultRepairPrice, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.FaultRepairPrice, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.FaultRepairPrice, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default"/>
            </div>
        </div>

        @foreach (var item in Model.FaultParts)
        {
            <div class="form-group">
                @Html.DisplayFor(m => item.Name)
                -
                @Html.DisplayFor(m => item.NetPrice) PLN
            </div>
        }
        <div class="form-group">
            @Html.ActionLink("Zarządzaj częściami", "Parts", new {Model.FaultId})
            <span class="lnr lnr-cog"></span>
        </div>


    </div>
}

<div>
    @Html.ActionLink("Powrót do listy usterek", "Index")
     <span class="lnr lnr-rocket"></span>
</div>

Handyman Studio/Views/Faults/Index.cshtml
@model IEnumerable<Handyman_Studio.Models.Fault>

@{
    ViewBag.Title = "Usterki";
}

<h2>Usterki</h2>

<p>
    @Html.ActionLink("Dodaj nową usterkę", "Create")
</p>
<input id="tableSearch" type="text" placeholder="Wyszukaj...">
<table class="table" id="searchTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FaultReportDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FaultRepairDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FaultSubject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FaultDescriptionUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FaultDescriptionService)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FaultPartPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FaultRepairPrice)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FaultReportDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FaultRepairDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FaultSubject)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FaultDescriptionUser)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FaultDescriptionService)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FaultPartPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FaultRepairPrice)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id=item.FaultId }) |
            @Html.ActionLink("Szczegóły", "Details", new { id=item.FaultId })
            @if ( item.ServicemanId.IsEmpty() || item.ServicemanId == "Nie przydzielono")
            {
                @:| @Html.ActionLink("Przyjmij", "Claim", new { id = item.FaultId })
            }
        </td>
    </tr>
}

</table>

Handyman Studio/Views/Faults/Parts.cshtml
@model Handyman_Studio.Models.FaultPartsModel

@{
    ViewBag.Title = "Części";
}
<h2>Części<span class="lnr lnr-cog"></span></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.FaultId)

        @foreach (var item in Model.FaultParts)
        {
            <div class="form-group">
                @Html.DisplayFor(m => item.Name)
                -
                @Html.DisplayFor(m => item.NetPrice) PLN

                @Html.ActionLink("Usuń część", "DeletePart", new { Model.FaultId, PartId = item.Id })
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.DropDownListFor(m => m.PartId, new SelectList(Model.AllParts, "Id", "Name", 0), "Wybierz część")
                <input type="submit" value="Dodaj część" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
    <span class="lnr lnr-rocket"></span>
</div>

Handyman Studio/Views/Faults/UserDetails.cshtml
@model Handyman_Studio.Models.Fault

<div>
    <h4>Szczegóły<span class="lnr lnr-star"></span></h4>



    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FaultId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServicemanId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServicemanId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultReportDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultReportDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultRepairDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultRepairDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultSubject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultSubject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultDescriptionUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultDescriptionUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultPartPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultPartPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultRepairPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultRepairPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultStatus)
        </dd>

    </dl>
</div>
<div class="col-xs-12">
    @Html.ActionLink("Powrót do listy usterek", "UserIndex")
        <span class="lnr lnr-rocket"></span>
</div>

Handyman Studio/Views/Faults/UserIndex.cshtml
@model IEnumerable<Handyman_Studio.Models.Fault>

<a href="/Products"> Moje urządzenia </a>

<p>
    @Html.ActionLink("Zgłoś nową usterkę", "Create")
</p>
<input id="tableSearch" type="text" placeholder="Wyszukaj...">
<table class="table" id="searchTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ServicemanId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FaultReportDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FaultRepairDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FaultSubject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FaultDescriptionUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FaultStatus)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ServicemanId)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FaultReportDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FaultRepairDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FaultSubject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FaultDescriptionUser)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FaultStatus)
            </td>
            <td>
                @Html.ActionLink("Szczegóły", "UserDetails", new { id = item.FaultId })
            </td>
        </tr>
    }

</table>