Handyman Studio/Controllers/AccountantPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Handyman_Studio.Models;
using Handyman_Studio.Utils;
using IronPdf;

namespace Handyman_Studio.Controllers
{
    public class AccountantPanelController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            if (!AccessCheck.Read(User.Identity.Name, PanelId.Accounting))
                return RedirectToAction("Index", "Home");

            var faultPartList = db.Faults.Select(fault => new FaultReport {Fault = fault, IsSelected = false});
            return View(faultPartList.ToList());
        }

        [HttpGet]
        public ActionResult Details(Guid? id)
        {
            if (!AccessCheck.Read(User.Identity.Name, PanelId.Accounting))
                return RedirectToAction("Index", "Home");

            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var fault = db.Faults.Find(id);
            if (fault == null) return HttpNotFound();
            return View(fault);
        }

        [HttpPost]
        public FileResult GenerateSingleReport(Guid selectedObject)
        {
            var fault = db.Faults.Find(selectedObject);
            var faultPartList = new List<Part>();
            var faultPart = db.FaultsParts.ToList();
            var renderer = new HtmlToPdf();

            foreach (var element in faultPart)
                if (element.FaultId == fault.FaultId)
                    faultPartList.Add(db.Parts.Find(element.PartId));

            var reportName = @"HMSFaultReport " + DateTime.Now + ".pdf";
            var user = db.Users.Find(fault.UserId);
            var client = new TransportData.ClientData
            {
                Name = user.Name,
                Surname = user.Surename,
                PhoneNumer = user.PhoneNumber,
                Mail = user.Email
            };
            return File(renderer.RenderHtmlAsPdf(HtmlGenerator.HtmlForFault(client,fault, faultPartList)).BinaryData,
                "application/pdf", reportName);
        }

        [HttpGet]
        public ActionResult GenerateCollectiveReport()
        {
            if (!AccessCheck.Write(User.Identity.Name, PanelId.Accounting))
                return RedirectToAction("Index", "Home");

            var faultPartList = db.Faults.Select(fault => new FaultReport {Fault = fault, IsSelected = false});
            return View(faultPartList.ToList());
        }

        [HttpPost]
        public FileResult GenerateCollectiveReport(Guid[] selectedObjects)
        {
            if (selectedObjects == null)
                return null;

            var faultList = selectedObjects.Select(id => db.Faults.Find(id)).ToList();
            var faultPartList = new List<Part>();

            var faultPart = db.FaultsParts.ToList();

            var renderer = new HtmlToPdf();
            var reports = new Queue<PdfDocument>();

            foreach (var fault in faultList)
            {
                foreach (var element in faultPart)
                    if (element.FaultId == fault.FaultId)
                        faultPartList.Add(db.Parts.Find(element.PartId));

                var user = db.Users.Find(fault.UserId);
                var client = new TransportData.ClientData
                {
                    Name = user.Name,
                    Surname = user.Surename,
                    PhoneNumer = user.PhoneNumber,
                    Mail = user.Email
                };

                reports.Enqueue(renderer.RenderHtmlAsPdf(HtmlGenerator.HtmlForFault(client, fault, faultPartList)));
            }

            var mergedPdfs = PdfDocument.Merge(reports);
            var reportName = @"HMSFaultsReport " + DateTime.Now + ".pdf";
            return File(mergedPdfs.BinaryData, "application/pdf", reportName);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Handyman Studio/Views/AccountantPanel/Details.cshtml
@model Handyman_Studio.Models.Fault

@{
    ViewBag.Title = "Szczegóły usterki";
}

<h2>Szczegóły usterki</h2>

<div>
    <h4>Usterka:</h4>
    <h5>@Html.DisplayFor(model => model.FaultId)</h5>
    <hr />
    @using (Html.BeginForm("GenerateSingleReport", "AccountantPanel", FormMethod.Post))
    {
        <input type="submit" value="Generuj raport"/>
        <input type="hidden"  name="selectedObject" value="@Model.FaultId">
    }
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServicemanId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServicemanId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultReportDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultReportDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultRepairDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultRepairDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultSubject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultSubject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultDescriptionUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultDescriptionUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultPartPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultPartPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultRepairPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultRepairPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaultStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaultStatus)
        </dd>

    </dl>

</div>
<p>
    @Html.ActionLink("Powrót to listy wszystkich usterek", "Index")
</p>

Handyman Studio/Views/AccountantPanel/GenerateCollectiveReport.cshtml
@model IEnumerable<Handyman_Studio.Models.FaultReport>

@{
    ViewBag.Title = "Lista usterek";
}

<h2>Lista usterek:</h2>
 
<div>
@using (Html.BeginForm("GenerateCollectiveReport"))
{
    <input type="submit" value="Generuj raport" />
    <table class="table">
        <tr>
            <th>
                Wybrane do raportu
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fault.FaultId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fault.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fault.ServicemanId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fault.FaultReportDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fault.FaultRepairDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fault.FaultSubject)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fault.FaultDescriptionUser)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fault.FaultPartPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fault.FaultRepairPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fault.FaultStatus)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                <input type="checkbox" name="selectedObjects" value="@item.Fault.FaultId">
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.ServicemanId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultReportDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultRepairDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultSubject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultDescriptionUser)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultPartPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultRepairPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultStatus)
            </td>
            <td>
                @Html.ActionLink("Szczegóły", "Details", new { id = item.Fault.FaultId })
            </td>
        </tr>

        }
    </table>
}
</div>

Handyman Studio/Views/AccountantPanel/Index.cshtml
@model IEnumerable<Handyman_Studio.Models.FaultReport>

@{
    ViewBag.Title = "Lista usterek";
    @Html.ActionLink("Generuj raport usterek","GenerateCollectiveReport")
}

<h2>Lista usterek:</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Fault.FaultId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fault.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fault.ServicemanId)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Fault.FaultReportDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fault.FaultRepairDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fault.FaultSubject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fault.FaultDescriptionUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fault.FaultPartPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fault.FaultRepairPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fault.FaultStatus)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.ServicemanId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultReportDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultRepairDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultSubject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultDescriptionUser)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultPartPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultRepairPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fault.FaultStatus)
            </td>
            <td>
                @Html.ActionLink("Szczegóły", "Details", new {id = item.Fault.FaultId})
            </td>
        </tr>
    }
</table>